### ISSUE TITLE
constant-candidates fails with: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by elopio** [elopio/solium-plugin-zeppelin#14]
I tried running the constant-candidates rule on the zeppelin-solidity project, and it failed with:

✖ [Fatal error] An error occurred while linting over /home/ubuntu/zeppelin-solidity/contracts/ownership/Heritable.sol: Cannot read property 'type' of null

**Comment by duaraghav8** [comment]
originates from https://github.com/elopio/solium-plugin-zeppelin/blob/master/rules/constant-candidates.js#L41 `node.value` seems to be `null`

I'll be pushing the ability to dump stack trace in the next release of solium, that will make life easier for plugin devs

**Comment by elopio** [comment]
Yay, thanks @duaraghav8! Just mentioning the rule in the error would be very useful. The trace even better.
